version: "3.8"

services:
  python:
    image: python:3.10-slim
    container_name: middlelayer
    ports:
      - "8888:8888"
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./neo4j/neo4j_import:/app/import
      - ~/.aws:/root/.aws:ro
    working_dir: /app
    command: bash -c "pip install --no-cache-dir duckdb awscli fastapi pyarrow jupyter numpy pandas && tail -f /dev/null"

  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    environment:
      NEO4J_AUTH: "neo4j/ldbc2727"
      NEO4J_PLUGINS: '["apoc", "apoc-extended", "graph-data-science"]'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
    volumes:
      - ./neo4j/neo4j_data:/data
      - ./neo4j/neo4j_logs:/logs
      - ./neo4j/neo4j_import:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"

  neodash:
    image: nielsdejong/neodash:latest
    container_name: neodash
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ldbc2727
    ports:
      - "5005:5005"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
